-- Nassau Academy English — Round 7a: AI voice audio (ElevenLabs)
-- Every line to record lives in audio_lines; the tts edge function generates the MP3s into the public "audio" bucket.

insert into storage.buckets (id, name, public) values ('audio', 'audio', true)
on conflict (id) do update set public = true;

create table if not exists public.audio_lines (
  id text primary key,                 -- E01-05 (episode line) or M1-L3-S1 (exercise clip)
  kind text not null check (kind in ('episode','exercise')),
  episode int,
  module int not null,
  step_id uuid references public.steps(id) on delete set null,
  lines jsonb not null,                -- [{speaker, text, say}] — say = text sent to the voice
  url text,
  chars int,
  generated_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.audio_lines enable row level security;
drop policy if exists "audio_lines: staff read" on public.audio_lines;
create policy "audio_lines: staff read" on public.audio_lines for select to authenticated using (public.is_staff());
drop policy if exists "audio_lines: admin edit" on public.audio_lines;
create policy "audio_lines: admin edit" on public.audio_lines for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- Voice settings (voice IDs are filled in by the admin in Admin → Audio)
insert into public.app_settings (key, value) values ('voices', jsonb_build_object(
  'model', 'eleven_multilingual_v2',
  'format', 'mp3_44100_192',
  'speed', jsonb_build_object('1', 0.9, '2', 0.95, '3', 1.0, '4', 1.0),
  'voices', '{}'::jsonb))
on conflict (key) do nothing;

create or replace function public.step_at(m int, l int, p int) returns uuid language sql stable set search_path = public as $$
  select s.id from steps s join lessons le on le.id = s.lesson_id join modules mo on mo.id = le.module_id
  join courses c on c.id = mo.course_id where c.code = 'en-a1-1' and mo.position = m and le.position = l and s.position = p;
$$;
revoke execute on function public.step_at(int,int,int) from public, anon, authenticated;

insert into public.audio_lines (id, kind, episode, module, step_id, lines) values
('E01-01','episode',1,1,null,'[{"speaker":"Jan","say":"Hello! Welcome to Nassau Academy."}]'::jsonb),
('E01-02','episode',1,1,null,'[{"speaker":"Luis","say":"Hi!"}]'::jsonb),
('E01-03','episode',1,1,null,'[{"speaker":"Jan","say":"I''m Jan. What''s your name?"}]'::jsonb),
('E01-04','episode',1,1,null,'[{"speaker":"Luis","say":"Am Luis."}]'::jsonb),
('E01-05','episode',1,1,null,'[{"speaker":"Jan","say":"\"I''m Luis.\" I''m… I am."}]'::jsonb),
('E01-06','episode',1,1,null,'[{"speaker":"Luis","say":"Oh! I''m Luis. My name is Luis."}]'::jsonb),
('E01-07','episode',1,1,null,'[{"speaker":"Jan","say":"Nice to meet you, Luis."}]'::jsonb),
('E01-08','episode',1,1,null,'[{"speaker":"Luis","say":"Nice to meet you too."}]'::jsonb),
('E01-09','episode',1,1,null,'[{"speaker":"Maya","say":"Hello! I''m Maya. What''s your name?"}]'::jsonb),
('E01-10','episode',1,1,null,'[{"speaker":"Luis","say":"Hi, Maya. My name is Luis. Nice to meet you."}]'::jsonb),
('E01-11','episode',1,1,null,'[{"speaker":"Maya","say":"Nice to meet you too."}]'::jsonb),
('E01-12','episode',1,1,null,'[{"speaker":"Sofía","say":"Hi. I''m Sofía."}]'::jsonb),
('E01-13','episode',1,1,null,'[{"speaker":"Luis","say":"Hello, Sofía! I''m Luis."}]'::jsonb),
('E01-14','episode',1,1,null,'[{"speaker":"Maya","say":"And I''m Maya. Nice to meet you, Sofía."}]'::jsonb),
('E01-15','episode',1,1,null,'[{"speaker":"Sofía","say":"Nice to meet you too."}]'::jsonb),
('E01-16','episode',1,1,null,'[{"speaker":"Jan","say":"Maya, Sofía, Luis… Where are you from?"}]'::jsonb),
('E01-17','episode',1,1,null,'[{"speaker":"Luis","say":"Um…"}]'::jsonb),
('E02-01','episode',2,1,null,'[{"speaker":"Maya","say":"Luis, where are you from?"}]'::jsonb),
('E02-02','episode',2,1,null,'[{"speaker":"Luis","say":"I''m from Colombian."}]'::jsonb),
('E02-03','episode',2,1,null,'[{"speaker":"Sofía","say":"No, Luis. \"I''m from Colombia.\" Colombia is the country."}]'::jsonb),
('E02-04','episode',2,1,null,'[{"speaker":"Luis","say":"Ah! I''m from Colombia. I''m Colombian."}]'::jsonb),
('E02-05','episode',2,1,null,'[{"speaker":"Maya","say":"Colombia! Nice!"}]'::jsonb),
('E02-06','episode',2,1,null,'[{"speaker":"Luis","say":"And you, Maya? Where are you from?"}]'::jsonb),
('E02-07','episode',2,1,null,'[{"speaker":"Maya","say":"I''m from Jamaica. I''m Jamaican."}]'::jsonb),
('E02-08','episode',2,1,null,'[{"speaker":"Luis","say":"Sofía, where are you from?"}]'::jsonb),
('E02-09','episode',2,1,null,'[{"speaker":"Sofía","say":"I''m from Venezuela. I''m Venezuelan."}]'::jsonb),
('E02-10','episode',2,1,null,'[{"speaker":"Jan","say":"Hi!"}]'::jsonb),
('E02-11','episode',2,1,null,'[{"speaker":"Maya","say":"Hi, Jan! Where are you from?"}]'::jsonb),
('E02-12','episode',2,1,null,'[{"speaker":"Jan","say":"I''m from the Netherlands. I''m Dutch."}]'::jsonb),
('E02-13','episode',2,1,null,'[{"speaker":"Luis","say":"Colombia, Venezuela, Jamaica, the Netherlands…"}]'::jsonb),
('E02-14','episode',2,1,null,'[{"speaker":"Maya","say":"Four countries. Photo!"}]'::jsonb),
('E02-15','episode',2,1,null,'[{"speaker":"Jan","say":"Now, your name badges. Luis, how do you spell your name?"}]'::jsonb),
('E02-16','episode',2,1,null,'[{"speaker":"Luis","say":"Um…"}]'::jsonb),
('E03-01','episode',3,1,null,'[{"speaker":"Jan","say":"OK. Name badges! Luis, how do you spell your name?"}]'::jsonb),
('E03-02','episode',3,1,null,'[{"speaker":"Luis","text":"L–U–I–S.","say":"L, U, I, S."}]'::jsonb),
('E03-03','episode',3,1,null,'[{"speaker":"Jan","text":"L–U–E–S?","say":"L, U, E, S?"}]'::jsonb),
('E03-04','episode',3,1,null,'[{"speaker":"Luis","text":"No, no! L–U–…","say":"No, no! L, U, …"}]'::jsonb),
('E03-05','episode',3,1,null,'[{"speaker":"Jan","say":"Sorry, can you repeat that?"}]'::jsonb),
('E03-06','episode',3,1,null,'[{"speaker":"Maya","say":"Luis, in English, E is \"ee\"… and I is \"eye\"."}]'::jsonb),
('E03-07','episode',3,1,null,'[{"speaker":"Luis","text":"Oh! L–U–I–S.","say":"Oh! L, U, I, S."}]'::jsonb),
('E03-08','episode',3,1,null,'[{"speaker":"Jan","text":"L–U–I–S. Luis. Perfect!","say":"L, U, I, S. Luis. Perfect!"}]'::jsonb),
('E03-09','episode',3,1,null,'[{"speaker":"Jan","say":"Sofía, how do you spell your name?"}]'::jsonb),
('E03-10','episode',3,1,null,'[{"speaker":"Sofía","text":"S–O–F–I–A.","say":"S, O, F, I, A."}]'::jsonb),
('E03-11','episode',3,1,null,'[{"speaker":"Jan","say":"Sorry, can you repeat the last letter?"}]'::jsonb),
('E03-12','episode',3,1,null,'[{"speaker":"Sofía","say":"A."}]'::jsonb),
('E03-13','episode',3,1,null,'[{"speaker":"Jan","text":"S–O–F–I–A. Thank you.","say":"S, O, F, I, A. Thank you."}]'::jsonb),
('E03-14','episode',3,1,null,'[{"speaker":"Maya","text":"And me: M–A–Y–A.","say":"And me: M, A, Y, A."}]'::jsonb),
('E03-15','episode',3,1,null,'[{"speaker":"Luis","say":"Jan, how do you spell \"Jan\"?"}]'::jsonb),
('E03-16','episode',3,1,null,'[{"speaker":"Jan","text":"J–A–N.","say":"J, A, N."}]'::jsonb),
('E04-01','episode',4,1,null,'[{"speaker":"Luis","say":"Hi! I''m Luis. What''s your name?"}]'::jsonb),
('E04-02','episode',4,1,null,'[{"speaker":"Emma","say":"Hello! My name is Emma."}]'::jsonb),
('E04-03','episode',4,1,null,'[{"speaker":"Luis","say":"Nice to meet you, Emma."}]'::jsonb),
('E04-04','episode',4,1,null,'[{"speaker":"Emma","say":"Nice to meet you too. Where are you from?"}]'::jsonb),
('E04-05','episode',4,1,null,'[{"speaker":"Luis","say":"I''m from Colombia. I''m Colombian. And you?"}]'::jsonb),
('E04-06','episode',4,1,null,'[{"speaker":"Emma","say":"I''m from Aruba. I''m Aruban."}]'::jsonb),
('E04-07','episode',4,1,null,'[{"speaker":"Luis","say":"How do you spell your name?"}]'::jsonb),
('E04-08','episode',4,1,null,'[{"speaker":"Emma","text":"E–M–M–…","say":"E, M, M, …"}]'::jsonb),
('E04-09','episode',4,1,null,'[{"speaker":"Luis","say":"Sorry, can you repeat the last letter?"}]'::jsonb),
('E04-10','episode',4,1,null,'[{"speaker":"Emma","text":"A. E–M–M–A.","say":"A. E, M, M, A."}]'::jsonb),
('E04-11','episode',4,1,null,'[{"speaker":"Luis","text":"E–M–M–A. Thank you!","say":"E, M, M, A. Thank you!"}]'::jsonb),
('E04-12','episode',4,1,null,'[{"speaker":"Sofía","say":"Very good, Luis!"}]'::jsonb),
('E04-13','episode',4,1,null,'[{"speaker":"Maya","say":"Photo!"}]'::jsonb),
('E04-14','episode',4,1,null,'[{"speaker":"Luis","say":"My bag… My bag! Where is my bag?"}]'::jsonb),
('E05-01','episode',5,2,null,'[{"speaker":"Maya","say":"Luis! Your bag?"}]'::jsonb),
('E05-02','episode',5,2,null,'[{"speaker":"Luis","say":"No bag. My phone, my photos… in my bag."}]'::jsonb),
('E05-03','episode',5,2,null,'[{"speaker":"Maya","say":"Oh no. Look, my photos. This is my family."}]'::jsonb),
('E05-04','episode',5,2,null,'[{"speaker":"Maya","say":"This is my mother, and this is my father. My parents."}]'::jsonb),
('E05-05','episode',5,2,null,'[{"speaker":"Sofía","say":"Parents… like parientes?"}]'::jsonb),
('E05-06','episode',5,2,null,'[{"speaker":"Maya","say":"No. Parents: mother and father."}]'::jsonb),
('E05-07','episode',5,2,null,'[{"speaker":"Maya","say":"This is my sister. Her name is Kim. And this is my brother. His name is Dean."}]'::jsonb),
('E05-08','episode',5,2,null,'[{"speaker":"Luis","say":"Her name is Kim… his name is Dean."}]'::jsonb),
('E05-09','episode',5,2,null,'[{"speaker":"Sofía","say":"Luis, your sister… What''s her name?"}]'::jsonb),
('E05-10','episode',5,2,null,'[{"speaker":"Luis","say":"Su name is Ana."}]'::jsonb),
('E05-11','episode',5,2,null,'[{"speaker":"Sofía","say":"Su? Ana is a woman: her name."}]'::jsonb),
('E05-12','episode',5,2,null,'[{"speaker":"Luis","say":"Her name is Ana. And my brother? His name is Pablo. My parents? Their names are Rosa and Jorge."}]'::jsonb),
('E05-13','episode',5,2,null,'[{"speaker":"Maya","say":"Our families are big!"}]'::jsonb),
('E05-14','episode',5,2,null,'[{"speaker":"Jan","say":"Luis! Your bag! A man from a shop on Handelskade… He has your bag!"}]'::jsonb),
('E05-15','episode',5,2,null,'[{"speaker":"Luis","say":"My bag! Let''s go!"}]'::jsonb),
('E06-01','episode',6,2,null,'[{"speaker":"Mr. Martis","say":"Hello! Your bag? What colour is it?"}]'::jsonb),
('E06-02','episode',6,2,null,'[{"speaker":"Luis","say":"It''s blue."}]'::jsonb),
('E06-03','episode',6,2,null,'[{"speaker":"Mr. Martis","say":"These bags are blue."}]'::jsonb),
('E06-04','episode',6,2,null,'[{"speaker":"Luis","say":"Blues bags…"}]'::jsonb),
('E06-05','episode',6,2,null,'[{"speaker":"Sofía","say":"\"Blue bags.\" Blue—no S."}]'::jsonb),
('E06-06','episode',6,2,null,'[{"speaker":"Luis","say":"These are blue bags… but not my bag."}]'::jsonb),
('E06-07','episode',6,2,null,'[{"speaker":"Maya","say":"Look! That building is yellow. Those buildings are green and pink!"}]'::jsonb),
('E06-08','episode',6,2,null,'[{"speaker":"Luis","say":"This is a pen. These are pens. This is a box. These are boxes. Two watches… three phones…"}]'::jsonb),
('E06-09','episode',6,2,null,'[{"speaker":"Sofía","say":"Are these your keys?"}]'::jsonb),
('E06-10','episode',6,2,null,'[{"speaker":"Luis","say":"No. My keys are in my bag."}]'::jsonb),
('E06-11','episode',6,2,null,'[{"speaker":"Jan","say":"Where is his bag?"}]'::jsonb),
('E06-12','episode',6,2,null,'[{"speaker":"Mr. Martis","say":"A woman has a blue bag. She is at the café. That café!"}]'::jsonb),
('E06-13','episode',6,2,null,'[{"speaker":"Luis","say":"A woman… but which woman?"}]'::jsonb),
('E07-01','episode',7,2,null,'[{"speaker":"Luis","say":"Hello. A woman has my bag. A blue bag."}]'::jsonb),
('E07-02','episode',7,2,null,'[{"speaker":"Waiter","say":"Ah, yes! She is young. She is short. She is long black hair."}]'::jsonb),
('E07-03','episode',7,2,null,'[{"speaker":"Sofía","say":"\"She has long black hair.\""}]'::jsonb),
('E07-04','episode',7,2,null,'[{"speaker":"Waiter","say":"Yes! She has long black hair."}]'::jsonb),
('E07-05','episode',7,2,null,'[{"speaker":"Maya","say":"That man is old. He has glasses. Not him."}]'::jsonb),
('E07-06','episode',7,2,null,'[{"speaker":"Jan","say":"That woman is tall. She has short brown hair. Not her."}]'::jsonb),
('E07-07','episode',7,2,null,'[{"speaker":"Luis","say":"Young… short… long black hair…"}]'::jsonb),
('E07-08','episode',7,2,null,'[{"speaker":"Emma","say":"Luis?"}]'::jsonb),
('E07-09','episode',7,2,null,'[{"speaker":"Luis","say":"Emma!"}]'::jsonb),
('E08-01','episode',8,2,null,'[{"speaker":"Emma","say":"Is this bag yours?"}]'::jsonb),
('E08-02','episode',8,2,null,'[{"speaker":"Luis","say":"Yes! It''s mine! Thank you!"}]'::jsonb),
('E08-03','episode',8,2,null,'[{"speaker":"Emma","text":"The badge says \"LUES\".","say":"The badge says: L, U, E, S."}]'::jsonb),
('E08-04','episode',8,2,null,'[{"speaker":"Sofía","say":"Is this phone yours, Luis?"}]'::jsonb),
('E08-05','episode',8,2,null,'[{"speaker":"Luis","say":"No, that phone is Maya''s. It''s hers."}]'::jsonb),
('E08-06','episode',8,2,null,'[{"speaker":"Jan","say":"And these keys? Are they his?"}]'::jsonb),
('E08-07','episode',8,2,null,'[{"speaker":"Maya","say":"Yes, they''re Luis''s keys."}]'::jsonb),
('E08-08','episode',8,2,null,'[{"speaker":"Emma","say":"Who is this?"}]'::jsonb),
('E08-09','episode',8,2,null,'[{"speaker":"Luis","say":"This is the mother of Luis…"}]'::jsonb),
('E08-10','episode',8,2,null,'[{"speaker":"Sofía","say":"\"Luis''s mother.\""}]'::jsonb),
('E08-11','episode',8,2,null,'[{"speaker":"Luis","say":"Yes! This is my mother, Rosa. This is Luis''s father… my father, Jorge. And this is my sister, Ana."}]'::jsonb),
('E08-12','episode',8,2,null,'[{"speaker":"Maya","say":"So Ana is Pablo''s sister too!"}]'::jsonb),
('E08-13','episode',8,2,null,'[{"speaker":"Luis","say":"My sister… Friday… in Curaçao!"}]'::jsonb),
('E09-01','episode',9,3,null,'[{"speaker":"Sofía","say":"OK. Ana is in Curaçao on Friday. What time?"}]'::jsonb),
('E09-02','episode',9,3,null,'[{"speaker":"Luis","say":"At five… in the afternoon."}]'::jsonb),
('E09-03','episode',9,3,null,'[{"speaker":"Jan","say":"Monday, Tuesday, Wednesday, Thursday… Friday!"}]'::jsonb),
('E09-04','episode',9,3,null,'[{"speaker":"Sofía","say":"On Friday, at five o''clock. At the airport."}]'::jsonb),
('E09-05','episode',9,3,null,'[{"speaker":"Maya","say":"And on Saturday? In the morning, the beach!"}]'::jsonb),
('E09-06','episode',9,3,null,'[{"speaker":"Jan","say":"On Sunday, in the evening, music in Punda!"}]'::jsonb),
('E09-07','episode',9,3,null,'[{"speaker":"Luis","say":"What time is it now?"}]'::jsonb),
('E09-08','episode',9,3,null,'[{"speaker":"Sofía","say":"Is ten o''clock."}]'::jsonb),
('E09-09','episode',9,3,null,'[{"speaker":"Maya","say":"\"It is ten o''clock.\" It''s ten o''clock."}]'::jsonb),
('E09-10','episode',9,3,null,'[{"speaker":"Sofía","say":"Oh! It''s ten o''clock. Thank you."}]'::jsonb),
('E09-11','episode',9,3,null,'[{"speaker":"Maya","say":"We have class on Monday, on Wednesday and on Friday."}]'::jsonb),
('E09-12','episode',9,3,null,'[{"speaker":"Luis","say":"Class on Friday? At five?"}]'::jsonb),
('E09-13','episode',9,3,null,'[{"speaker":"Sofía","say":"No. Class is in the morning, at nine o''clock."}]'::jsonb),
('E09-14','episode',9,3,null,'[{"speaker":"Jan","say":"Luis… what time do you wake up?"}]'::jsonb),
('E09-15','episode',9,3,null,'[{"speaker":"Luis","say":"Um…"}]'::jsonb),
('E10-01','episode',10,3,null,'[{"speaker":"Sofía","say":"Every day, I wake up at six o''clock."}]'::jsonb),
('E10-02','episode',10,3,null,'[{"speaker":"Sofía","say":"I take a shower. I get dressed. I eat breakfast at six thirty. I drink coffee."}]'::jsonb),
('E10-03','episode',10,3,null,'[{"speaker":"Sofía","say":"I go to class at eight thirty."}]'::jsonb),
('E10-04','episode',10,3,null,'[{"speaker":"Luis","say":"Every day, I am waking up at eight fifty!"}]'::jsonb),
('E10-05','episode',10,3,null,'[{"speaker":"Maya","say":"\"I wake up.\" Every day, I wake up."}]'::jsonb),
('E10-06','episode',10,3,null,'[{"speaker":"Luis","say":"Every day, I wake up at eight fifty! I take a shower… no! I drink coffee! I go to class!"}]'::jsonb),
('E10-07','episode',10,3,null,'[{"speaker":"Jan","say":"Luis, it''s nine ten!"}]'::jsonb),
('E10-08','episode',10,3,null,'[{"speaker":"Luis","say":"Sorry, sorry!"}]'::jsonb),
('E10-09','episode',10,3,null,'[{"speaker":"Maya","say":"And Ana? What time does she wake up?"}]'::jsonb),
('E10-10','episode',10,3,null,'[{"speaker":"Luis","say":"Ana? Oh… Ana is very different."}]'::jsonb),
('E11-01','episode',11,3,null,'[{"speaker":"Luis","say":"Ana is a nurse. She work in a hospital."}]'::jsonb),
('E11-02','episode',11,3,null,'[{"speaker":"Sofía","say":"\"She works.\" Works."}]'::jsonb),
('E11-03','episode',11,3,null,'[{"speaker":"Luis","say":"She works in a hospital. She wakes up at five o''clock. She plays volleyball. She watches TV every night."}]'::jsonb),
('E11-04','episode',11,3,null,'[{"speaker":"Maya","say":"And Jan? Jan works at reception. He plays the guitar. He watches football."}]'::jsonb),
('E11-05','episode',11,3,null,'[{"speaker":"Jan","say":"And Sofía wakes up at six o''clock. She drinks coffee. She goes to class at eight thirty."}]'::jsonb),
('E11-06','episode',11,3,null,'[{"speaker":"Sofía","say":"And Luis…"}]'::jsonb),
('E11-07','episode',11,3,null,'[{"speaker":"All","say":"…wakes up late!"}]'::jsonb),
('E11-08','episode',11,3,null,'[{"speaker":"Maya","say":"Luis''s parents work in Colombia. They work… no -s!"}]'::jsonb),
('E11-09','episode',11,3,null,'[{"speaker":"Sofía","say":"OK, everyone. A plan for Ana''s week!"}]'::jsonb),
('E12-01','episode',12,3,null,'[{"speaker":"Luis","say":"I always am late."}]'::jsonb),
('E12-02','episode',12,3,null,'[{"speaker":"Sofía","say":"\"I am always late.\" After am."}]'::jsonb),
('E12-03','episode',12,3,null,'[{"speaker":"Luis","say":"I am always late. But Ana is never late."}]'::jsonb),
('E12-04','episode',12,3,null,'[{"speaker":"Jan","say":"We usually eat at the snack truck on Saturday."}]'::jsonb),
('E12-05','episode',12,3,null,'[{"speaker":"Maya","say":"I sometimes take photos…"}]'::jsonb),
('E12-06','episode',12,3,null,'[{"speaker":"All","say":"You always take photos!"}]'::jsonb),
('E12-07','episode',12,3,null,'[{"speaker":"Maya","say":"OK, OK. I always take photos!"}]'::jsonb),
('E12-08','episode',12,3,null,'[{"speaker":"Sofía","say":"On Friday, at five o''clock: the airport. Luis, you are never late on Friday!"}]'::jsonb),
('E12-09','episode',12,3,null,'[{"speaker":"Jan","say":"Luis! It''s four fifty!"}]'::jsonb),
('E12-10','episode',12,3,null,'[{"speaker":"Luis","say":"I am never late for my sister!"}]'::jsonb),
('E12-11','episode',12,3,null,'[{"speaker":"Ana","say":"Luis!"}]'::jsonb),
('E12-12','episode',12,3,null,'[{"speaker":"Luis","say":"Ana! Welcome to Curaçao! This is Sofía, Maya and Jan."}]'::jsonb),
('E12-13','episode',12,3,null,'[{"speaker":"Ana","say":"Nice to meet you! Luis… where is my hotel?"}]'::jsonb),
('E12-14','episode',12,3,null,'[{"speaker":"Luis","say":"Um…"}]'::jsonb),
('E13-01','episode',13,4,null,'[{"speaker":"Ana","say":"The hotel is here?"}]'::jsonb),
('E13-02','episode',13,4,null,'[{"speaker":"Jan","say":"\"Is the hotel here?\" No. Go straight. Then turn left."}]'::jsonb),
('E13-03','episode',13,4,null,'[{"speaker":"Ana","say":"Where is the bank?"}]'::jsonb),
('E13-04','episode',13,4,null,'[{"speaker":"Maya","say":"The bank is there. And that is a restaurant."}]'::jsonb),
('E13-05','episode',13,4,null,'[{"speaker":"Ana","say":"Is there a library? I want a book."}]'::jsonb),
('E13-06','episode',13,4,null,'[{"speaker":"Luis","say":"A library!"}]'::jsonb),
('E13-07','episode',13,4,null,'[{"speaker":"Sofía","say":"Luis, a library is not a librería. In a library, you read. A bookshop sells books."}]'::jsonb),
('E13-08','episode',13,4,null,'[{"speaker":"Jan","say":"The bookshop is there. Turn right."}]'::jsonb),
('E13-09','episode',13,4,null,'[{"speaker":"Ana","say":"And where is the hospital? I am a nurse."}]'::jsonb),
('E13-10','episode',13,4,null,'[{"speaker":"Jan","say":"The hospital is not in Punda. Go straight over the bridge."}]'::jsonb),
('E13-11','episode',13,4,null,'[{"speaker":"Jan","say":"Your hotel!"}]'::jsonb),
('E13-12','episode',13,4,null,'[{"speaker":"Ana","say":"Thank you, Jan! Tomorrow, where do we meet?"}]'::jsonb),
('E13-13','episode',13,4,null,'[{"speaker":"Luis","say":"Meet me in the bridge!"}]'::jsonb),
('E14-01','episode',14,4,null,'[{"speaker":"Maya","say":"I''m on Handelskade, next to the yellow building."}]'::jsonb),
('E14-02','episode',14,4,null,'[{"speaker":"Sofía","say":"I''m at the bus stop, between the bank and the library."}]'::jsonb),
('E14-03','episode',14,4,null,'[{"speaker":"Jan","say":"I''m at the café, in Punda."}]'::jsonb),
('E14-04','episode',14,4,null,'[{"speaker":"Luis","say":"I''m in the bridge!"}]'::jsonb),
('E14-05','episode',14,4,null,'[{"speaker":"Jan","say":"In the bridge? In the water?"}]'::jsonb),
('E14-06','episode',14,4,null,'[{"speaker":"Sofía","say":"\"On the bridge\" — on top. Or \"at the bridge\" — a point to meet."}]'::jsonb),
('E14-07','episode',14,4,null,'[{"speaker":"Luis","say":"OK! I''m at the bridge. Ana is with me. We live in Otrobanda."}]'::jsonb),
('E14-08','episode',14,4,null,'[{"speaker":"Maya","say":"Luis! We are in Punda. You are in Otrobanda!"}]'::jsonb),
('E14-09','episode',14,4,null,'[{"speaker":"Ana","say":"And I am hungry. Is there a restaurant in Otrobanda?"}]'::jsonb),
('E15-01','episode',15,4,null,'[{"speaker":"Ana","say":"Look! There is bananas!"}]'::jsonb),
('E15-02','episode',15,4,null,'[{"speaker":"Maya","say":"\"There are bananas.\" Two, three, many: there are."}]'::jsonb),
('E15-03','episode',15,4,null,'[{"speaker":"Ana","say":"There are bananas. And there is a papaya!"}]'::jsonb),
('E15-04','episode',15,4,null,'[{"speaker":"Sofía","say":"Are there any mangoes?"}]'::jsonb),
('E15-05','episode',15,4,null,'[{"speaker":"Seller","say":"Yes, there are some mangoes. Green mangoes and red mangoes."}]'::jsonb),
('E15-06','episode',15,4,null,'[{"speaker":"Luis","say":"Is there any water?"}]'::jsonb),
('E15-07','episode',15,4,null,'[{"speaker":"Seller","say":"Sorry, there isn''t any water. There is a snack truck on that street."}]'::jsonb),
('E15-08','episode',15,4,null,'[{"speaker":"Jan","say":"In Curaçao, there are many snack trucks!"}]'::jsonb),
('E15-09','episode',15,4,null,'[{"speaker":"Ana","say":"There is an egg sandwich… there are some fries… there is a big menu!"}]'::jsonb),
('E15-10','episode',15,4,null,'[{"speaker":"Jan","say":"And on Saturday, there is a party at the beach!"}]'::jsonb),
('E15-11','episode',15,4,null,'[{"speaker":"All","say":"A party!"}]'::jsonb),
('E16-01','episode',16,4,null,'[{"speaker":"Emma","say":"Hi! I''m Emma. What''s your name?"}]'::jsonb),
('E16-02','episode',16,4,null,'[{"speaker":"Ana","say":"Hello! My name is Ana. Nice to meet you."}]'::jsonb),
('E16-03','episode',16,4,null,'[{"speaker":"Emma","say":"Nice to meet you too. Where are you from?"}]'::jsonb),
('E16-04','episode',16,4,null,'[{"speaker":"Ana","say":"I''m from Colombia. I''m Colombian. I''m twenty-six."}]'::jsonb),
('E16-05','episode',16,4,null,'[{"speaker":"Emma","say":"How do you spell your name?"}]'::jsonb),
('E16-06','episode',16,4,null,'[{"speaker":"Ana","text":"A–N–A. Easy!","say":"A, N, A. Easy!"}]'::jsonb),
('E16-07','episode',16,4,null,'[{"speaker":"Luis","say":"Ana is my sister. She is tall. She has short brown hair."}]'::jsonb),
('E16-08','episode',16,4,null,'[{"speaker":"Sofía","say":"She works in a hospital. She always wakes up at five o''clock!"}]'::jsonb),
('E16-09','episode',16,4,null,'[{"speaker":"Ana","say":"And Luis is always late!"}]'::jsonb),
('E16-10','episode',16,4,null,'[{"speaker":"Luis","say":"Not today! It''s six o''clock. I''m on time!"}]'::jsonb),
('E16-11','episode',16,4,null,'[{"speaker":"Jan","say":"Ana, is there an English class for you at Nassau Academy?"}]'::jsonb),
('E16-12','episode',16,4,null,'[{"speaker":"Ana","say":"Is there?"}]'::jsonb),
('E16-13','episode',16,4,null,'[{"speaker":"Jan","say":"Yes! On Monday, at nine o''clock, in the morning."}]'::jsonb),
('E16-14','episode',16,4,null,'[{"speaker":"Ana","say":"I am never late!"}]'::jsonb),
('E16-15','episode',16,4,null,'[{"speaker":"Maya","say":"Photo! Everyone!"}]'::jsonb),
('M1-L1-S1','exercise',null,1,public.step_at(1,1,1),'[{"speaker":"Maya","say":"Hello! I’m Maya. What’s your name?"},{"speaker":"Luis","say":"Hi, Maya. My name is Luis. Nice to meet you."},{"speaker":"Maya","say":"Nice to meet you too."}]'::jsonb),
('M1-L1-S2','exercise',null,1,public.step_at(1,1,2),'[{"speaker":"Maya","say":"Hello! I’m Maya. What’s your name?"}]'::jsonb),
('M1-L2-S1','exercise',null,1,public.step_at(1,2,1),'[{"speaker":"Luis","say":"Hi, Maya. Where are you from?"},{"speaker":"Maya","say":"I’m from Jamaica. I’m Jamaican. And you?"},{"speaker":"Luis","say":"I’m from Colombia. I’m Colombian."}]'::jsonb),
('M1-L2-S3','exercise',null,1,public.step_at(1,2,3),'[{"speaker":"Maya","say":"I’m from Jamaica. I’m Jamaican."}]'::jsonb),
('M1-L3-S1','exercise',null,1,public.step_at(1,3,1),'[{"speaker":"Jan","say":"I have your name as Karla, with a K. Is that correct?"},{"speaker":"Carla","say":"No. It’s Carla, with a C."},{"speaker":"Jan","say":"Sorry. How do you spell Carla?"},{"speaker":"Carla","text":"C–A–R–L–A.","say":"C, A, R, L, A."},{"speaker":"Jan","text":"Thank you. C–A–R–L–A. Correct?","say":"Thank you. C, A, R, L, A. Correct?"},{"speaker":"Carla","say":"Yes, that’s correct."}]'::jsonb),
('M1-L3-S2','exercise',null,1,public.step_at(1,3,2),'[{"speaker":"Nate","text":"A, H, J, K.","say":"A <break time=\"1.2s\" /> H <break time=\"1.2s\" /> J <break time=\"1.2s\" /> K."},{"speaker":"Nate","text":"B, C, D, E, G, P, T, V, Z.","say":"B <break time=\"1.2s\" /> C <break time=\"1.2s\" /> D <break time=\"1.2s\" /> E <break time=\"1.2s\" /> G <break time=\"1.2s\" /> P <break time=\"1.2s\" /> T <break time=\"1.2s\" /> V <break time=\"1.2s\" /> Z."},{"speaker":"Nate","text":"F, L, M, N, S, X.","say":"F <break time=\"1.2s\" /> L <break time=\"1.2s\" /> M <break time=\"1.2s\" /> N <break time=\"1.2s\" /> S <break time=\"1.2s\" /> X."},{"speaker":"Nate","text":"I, Y.","say":"I <break time=\"1.2s\" /> Y."},{"speaker":"Nate","say":"O."},{"speaker":"Nate","text":"Q, U, W.","say":"Q <break time=\"1.2s\" /> U <break time=\"1.2s\" /> W."},{"speaker":"Nate","say":"R."}]'::jsonb),
('M1-L3-S3','exercise',null,1,public.step_at(1,3,3),'[{"speaker":"Nate","say":"E."}]'::jsonb),
('M1-L3-S4','exercise',null,1,public.step_at(1,3,4),'[{"speaker":"Nate","say":"B, E."}]'::jsonb),
('M1-L3-S5','exercise',null,1,public.step_at(1,3,5),'[{"speaker":"Nate","say":"A, N, A."}]'::jsonb),
('M2-L1-S4','exercise',null,2,public.step_at(2,1,4),'[{"speaker":"Maya","say":"Look, my photos. This is my family."},{"speaker":"Maya","say":"This is my mother, and this is my father. My parents."},{"speaker":"Sofía","say":"Parents… like parientes?"},{"speaker":"Maya","say":"No. Parents: mother and father."},{"speaker":"Luis","say":"My sister? Her name is Ana. My parents? Their names are Rosa and Jorge."}]'::jsonb),
('M2-L2-S4','exercise',null,2,public.step_at(2,2,4),'[{"speaker":"Mr. Martis","say":"Your bag? What colour is it?"},{"speaker":"Luis","say":"It’s blue."},{"speaker":"Mr. Martis","say":"These bags are blue."},{"speaker":"Luis","say":"Blues bags…"},{"speaker":"Sofía","say":"Blue bags. Blue, no S."},{"speaker":"Luis","say":"This is a pen. These are pens. This is a box. These are boxes."}]'::jsonb),
('M2-L3-S4','exercise',null,2,public.step_at(2,3,4),'[{"speaker":"Luis","say":"A woman has my bag. A blue bag."},{"speaker":"Waiter","say":"She is young. She is short. She is long black hair."},{"speaker":"Sofía","say":"She has long black hair."},{"speaker":"Waiter","say":"Yes! She has long black hair."},{"speaker":"Maya","say":"That man is old. He has glasses. Not him."}]'::jsonb),
('M2-L4-S4','exercise',null,2,public.step_at(2,4,4),'[{"speaker":"Emma","say":"Is this bag yours?"},{"speaker":"Luis","say":"Yes! It’s mine! Thank you!"},{"speaker":"Sofía","say":"Is this phone yours, Luis?"},{"speaker":"Luis","say":"No, that phone is Maya’s. It’s hers."},{"speaker":"Luis","say":"This is the mother of Luis…"},{"speaker":"Sofía","say":"Luis’s mother."}]'::jsonb),
('M3-L1-S4','exercise',null,3,public.step_at(3,1,4),'[{"speaker":"Sofía","say":"Ana is in Curaçao on Friday. What time?"},{"speaker":"Luis","say":"At five… in the afternoon."},{"speaker":"Luis","say":"What time is it now?"},{"speaker":"Sofía","say":"Is ten o’clock."},{"speaker":"Maya","say":"It is ten o’clock. It’s ten o’clock."}]'::jsonb),
('M3-L2-S4','exercise',null,3,public.step_at(3,2,4),'[{"speaker":"Sofía","say":"Every day, I wake up at six o’clock."},{"speaker":"Sofía","say":"I take a shower. I get dressed. I eat breakfast at six thirty."},{"speaker":"Luis","say":"Every day, I am waking up at eight fifty!"},{"speaker":"Maya","say":"I wake up. Every day, I wake up."}]'::jsonb),
('M3-L3-S4','exercise',null,3,public.step_at(3,3,4),'[{"speaker":"Luis","say":"Ana is a nurse. She work in a hospital."},{"speaker":"Sofía","say":"She works. Works."},{"speaker":"Luis","say":"She works in a hospital. She wakes up at five o’clock. She plays volleyball. She watches TV every night."}]'::jsonb),
('M3-L4-S4','exercise',null,3,public.step_at(3,4,4),'[{"speaker":"Luis","say":"I always am late."},{"speaker":"Sofía","say":"I am always late. After am."},{"speaker":"Luis","say":"I am always late. But Ana is never late."},{"speaker":"Jan","say":"We usually eat at the snack truck on Saturday."},{"speaker":"Maya","say":"I always take photos!"}]'::jsonb),
('M4-L1-S4','exercise',null,4,public.step_at(4,1,4),'[{"speaker":"Ana","say":"The hotel is here?"},{"speaker":"Jan","say":"Is the hotel here? No. Go straight. Then turn left."},{"speaker":"Ana","say":"Is there a library? I want a book."},{"speaker":"Sofía","say":"A library is not a librería. A bookshop sells books."}]'::jsonb),
('M4-L2-S4','exercise',null,4,public.step_at(4,2,4),'[{"speaker":"Maya","say":"I’m on Handelskade, next to the yellow building."},{"speaker":"Sofía","say":"I’m at the bus stop, between the bank and the library."},{"speaker":"Luis","say":"I’m in the bridge!"},{"speaker":"Jan","say":"In the bridge? In the water?"},{"speaker":"Sofía","say":"On the bridge: on top. Or at the bridge: a point to meet."}]'::jsonb),
('M4-L3-S4','exercise',null,4,public.step_at(4,3,4),'[{"speaker":"Ana","say":"Look! There is bananas!"},{"speaker":"Maya","say":"There are bananas. Two, three, many: there are."},{"speaker":"Sofía","say":"Are there any mangoes?"},{"speaker":"Seller","say":"Yes, there are some mangoes."},{"speaker":"Luis","say":"Is there any water?"},{"speaker":"Seller","say":"Sorry, there isn’t any water."}]'::jsonb),
('M4-L4-S5','exercise',null,4,public.step_at(4,4,5),'[{"speaker":"Emma","say":"Hi! I’m Emma. What’s your name?"},{"speaker":"Ana","say":"Hello! My name is Ana. I’m from Colombia. I’m twenty-six."},{"speaker":"Luis","say":"Ana is my sister. She is tall. She has short brown hair."},{"speaker":"Sofía","say":"She works in a hospital. She always wakes up at five o’clock!"},{"speaker":"Jan","say":"Is there an English class for you? Yes! On Monday, at nine o’clock."}]'::jsonb)
on conflict (id) do update set lines = excluded.lines, step_id = excluded.step_id, module = excluded.module, updated_at = now();
